#!/bin/bash
    sudo apt-get update
    sudo apt-get install -y openjdk-8-jdk
    sudo apt install default-jre
    sudo apt install default-jdk
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
    /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null'
    sudo apt-get update
    sudo apt-get install -y jenkins
    sudo systemctl start jenkins
    sudo systemctl enable jenkins
    sudo apt-get install -y docker.io
    sudo usermod -aG docker jenkins
    sudo systemctl start docker
    sudo systemctl enable docker
